### ISSUE TITLE
插件安装完，无法添加股票代码

### ISSUE THREAD

**Issue by waltertan1988** [WhiteVermouth/intellij-investor-dashboard#18]
IDEA版本及运行信息：
IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

现象：
Tools/Stocker/Add Stock Code，点击右边的“add”按钮后，没看到任何反应。

**Comment by WhiteVermouth** [comment]
目前最低支持的IntelliJ版本是2021.1，2021.1之前的版本因API改动无法兼容。

**Comment by zsjlovelike** [comment]
> 目前最低支持的IntelliJ版本是2021.1，2021.1之前的版本因API改动无法兼容。

同样无法添加股票。报错内容不太一样，也是idea版本问题？
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 9
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at java.base/java.lang.String.subSequence(String.java:1913)
	at com.vermouthx.stocker.utils.StockerQuoteHttpUtil.validateCode(StockerQuoteHttpUtil.kt:74)
	at com.vermouthx.stocker.utils.StockerActionUtil.addStock(StockerActionUtil.java:18)
	at com.vermouthx.stocker.views.StockerStockAddDialog.lambda$setupStockSymbols$0(StockerStockAddDialog.java:112)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)

**Comment by yyconstantine** [comment]
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

无法添加股票
