### ISSUE TITLE
无法添加大A的票 IDEA 2020 2.3

### ISSUE THREAD

**Issue by ICLXL** [WhiteVermouth/intellij-investor-dashboard#2]

**Comment by WhiteVermouth** [comment]
股票代码是什么？有没有加上sh或sz前缀？

**Comment by ICLXL** [comment]
600702

**Comment by WhiteVermouth** [comment]
输入sh600702

**Comment by ICLXL** [comment]
这个试了 依旧不行

**Comment by ICLXL** [comment]
老铁加个日志啊.不然没法排查我本地到底啥问题加不上去

**Comment by WhiteVermouth** [comment]
https://www.jetbrains.com/help/idea/tuning-the-ide.html?_ga=2.11242935.206513735.1606655680-1650010321.1602492368#config-directory 
根据这个文档到IDEA的配置目录下，找到options/stocker-config.xml，比如macOS是~/Library/Application Support/JetBrains/IntelliJIdea2020.2/options/stocker-config.xml，把这个XML文件删掉，重启IDE，再添加试下，如果运行时产生了error，IDEA右下角应该是会出现感叹号报错的。

**Comment by ICLXL** [comment]
java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 6
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at java.base/java.lang.String.subSequence(String.java:1913)
	at com.vermouthx.stocker.utils.StockerQuoteHttpUtil.validateCode(StockerQuoteHttpUtil.kt:59)
	at com.vermouthx.stocker.actions.StockerStockAddAction.actionPerformed(StockerStockAddAction.kt:29)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:282)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:276)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:155)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:439)
	at java.desktop/java.awt.Component.processEvent(Component.java:6419)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5029)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2773)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4861)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:838)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:505)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

![image](https://user-images.githubusercontent.com/30027321/100713525-6505a080-33ef-11eb-8ec2-ac96304d4e31.png)

v1.0.0

老铁,等着用呢

**Comment by WhiteVermouth** [comment]
很奇怪，似乎是接口返回的响应不正常
```shell
curl "http://hq.sinajs.cn/list=sh600702"
```
在你出错的网络环境下跑一下上面的命令，看下返回结果

**Comment by ICLXL** [comment]
我日,还真是,我司把这个域名禁掉了,大佬可以针对这个插件单独设置一下proxy吗?我开全局proxy 可以了

**Comment by WhiteVermouth** [comment]
之后的版本可以考虑加下Proxy设置
